version: 0.2
phases: 
  install:
    on-failure: CONTINUE
    commands: 
      - "echo Entered the install phase..."
      - "apt-get update -y"
      - "apt-get install"
      - "apt-get install ca-certificates -y"
      - "apt-get install curl -y"
      - "apt-get install gnupg -y"
      - "apt-get install lsb-release -y"
      - "curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg"
      - "echo  \"deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu  $(lsb_release -cs) stable\" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null"
      - "apt-get update -y"
      - "apt-get install docker-ce docker-ce-cli containerd.io -y"
      - systemctl start docker
    finally: 
      - "echo This always runs even if the update or install command fails"

  pre_build: 
    commands: 
      - "echo Entered the pre_build phase..."
      - "docker ps"
    finally: 
      - "echo This always runs even if the login command fails"
    on-failure: CONTINUE

  build: 
    commands: 
      - "echo Entered the build phase..."
      - "echo Build started on `date`"
    finally: 
      - "echo This always runs even if the install command fails"

  post_build: 
    commands: 
      - "echo Entered the post_build phase..."
      - "echo Build completed on `date`"
      - "docker run hello-world"
