version: 2
plan:
  project-key: TDS
  key: PLAN
  name: My Plan

stages:
  - Stage 1:
      jobs:
        - Job 1

Job 1:
  tasks:
    - script:
        - printenv
        - docker run --rm --mount type=bind,source="$PWD",target=/scan registry.fortidevsec.forticloud.com/fdevsec_sast:latest env
