version: 2
plan:
  project-key: DIL
  key: PLAN
  name: My Plan

stages:
  - Stage 1:
      jobs:
        - Job 1

Job 1:
  tasks:
    - script:
        - printenv
        - echo 'Hello from YAML Specs'
